INSERT INTO counties (county_name, state_id) VALUES ("Adams", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Asotin", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Benton", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Chelan", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Clallam", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Clark", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Columbia", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Cowlitz", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Douglas", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Ferry", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Franklin", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Garfield", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Grant", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Grays Harbor", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Island", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Jefferson", 1);
INSERT INTO counties (county_name, state_id) VALUES ("King", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Kitsap", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Kittitas", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Klickitat", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Lewis", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Lincoln", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Mason", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Okanogan", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Pacific", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Pend Orielle", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Pierce", 1);
INSERT INTO counties (county_name, state_id) VALUES ("San Juan", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Skagit", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Skamania", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Snohomish", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Spokane", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Stevens", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Thurston", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Wahkiakum", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Walla Walla", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Whatcom", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Whitman", 1);
INSERT INTO counties (county_name, state_id) VALUES ("Yakima", 1);
