INSERT INTO destination_facility (facility_name, state_id) VALUES ("Airway Heights Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Cedar Creek Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Clallam Bay Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Colville Tribal Correctional Facility",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Coyote Ridge Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Issaquah Jail",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Kent City Corrections",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Larch Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Marysville City Jail",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("McNeil Island Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Mission Creek Corrections Center for Women",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Monroe Correctional Complex",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Nisqually Corrections",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Olympic Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Port Angeles City Jail",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Puyallup Tribal Jail",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("SCORE Jail",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Stafford Creek Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Washington Corrections Center",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Washington Corrections Center for Women",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Washington State Penitentiary",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Auburn",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Algona",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Beaux Arts",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Bellevue",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Federal Way",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Issaquah",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Kenmore",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Kent",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("King County Sherrif's Office",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Maple Valley",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("New Castle",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("North Bend",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Redmond",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Renton",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Sammamish",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("SeaTac",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Seattle(SPD and SMC)",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Shoreline",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Skykomish",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Tukwila",1);
INSERT INTO destination_facility (facility_name, state_id) VALUES ("Woodinville",1);